# Generated by Django 6.0.3 on 2026-03-27 19:54

import datetime
import django.db.models.deletion
import encrypted_model_fields.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdultStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Порядковый номер в году')),
                ('statement_year', models.PositiveSmallIntegerField(db_index=True, editable=False, verbose_name='Год ведомости')),
                ('fio', encrypted_model_fields.fields.EncryptedCharField(verbose_name='ФИО')),
                ('phone_number', encrypted_model_fields.fields.EncryptedCharField(db_index=True, verbose_name='Номер телефона')),
                ('course_name', models.CharField(choices=[('A', 'A'), ('A+B', 'A+B'), ('A1', 'A1'), ('A1+A+B', 'A1+A+B'), ('A1+B', 'A1+B'), ('АЗИЯ', 'АЗИЯ'), ('БАЗА', 'БАЗА'), ('БАЗА индив', 'БАЗА индив'), ('КОНТР', 'КОНТР'), ('КОНТР индив', 'КОНТР индив'), ('МИНИ', 'МИНИ'), ('МИНИ индив', 'МИНИ индив'), ('ПРО', 'ПРО'), ('ПРО индив', 'ПРО индив'), ('ПРОБНОЕ', 'ПРОБНОЕ'), ('ПРОБНОЕ индив', 'ПРОБНОЕ индив'), ('РАЗОВОЕ', 'РАЗОВОЕ'), ('РАЗОВОЕ индив', 'РАЗОВОЕ индив'), ('СЕКЦИЯ', 'СЕКЦИЯ'), ('СЕРТИФИКАТ', 'СЕРТИФИКАТ'), ('СТАНДАРТ', 'СТАНДАРТ'), ('СТАНДАРТ индив', 'СТАНДАРТ индив'), ('ЭКСТРА', 'ЭКСТРА'), ('ЭКСТРА индив', 'ЭКСТРА индив'), ('VIP', 'VIP')], max_length=50, verbose_name='Название курса')),
                ('total_hours', models.IntegerField(blank=True, null=True, verbose_name='Всего часов')),
                ('rolled_back_hours', models.IntegerField(default=0, verbose_name='Откатанные часы')),
                ('first_visit_date', models.DateField(blank=True, null=True, verbose_name='Первое посещение')),
                ('date_of_buyback', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('summ_of_payback', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('comment_for_payback', models.TextField(blank=True, null=True, verbose_name='Комментарий по оплате')),
                ('is_refund', models.BooleanField(default=False, verbose_name='Возврат средств')),
                ('summ_of_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма возврата')),
                ('school_name', models.CharField(blank=True, choices=[('НУР', 'НУР'), ('ДВИЖ', 'ДВИЖ')], max_length=10, null=True, verbose_name='Школа')),
                ('documents', models.BooleanField(default=False, verbose_name='Документы')),
                ('internal_examination', models.BooleanField(default=False, verbose_name='Внутренний экзамен')),
                ('gai_examination', models.BooleanField(default=False, verbose_name='Экзамен в ГАИ')),
                ('transferred_the_certificate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Свидетельство передано/дата/комментарии')),
                ('is_in_office', models.BooleanField(default=False, verbose_name='В офисе')),
                ('is_manually_closed', models.BooleanField(default=False, verbose_name='Ведомость закрыта вручную')),
            ],
            options={
                'verbose_name': 'Взрослый студент',
                'verbose_name_plural': 'Взрослые студенты',
                'ordering': ['-statement_year', '-sequence_number'],
                'unique_together': {('sequence_number', 'statement_year')},
            },
        ),
        migrations.CreateModel(
            name='AdultRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_snapshot', models.CharField(max_length=255, verbose_name='ФИО (на момент возврата)')),
                ('course_name_snapshot', models.CharField(max_length=255, verbose_name='Курс (на момент возврата)')),
                ('summ_of_refund', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма возврата')),
                ('date_of_refund', models.DateField(default=datetime.date.today, verbose_name='Дата возврата')),
                ('comment_for_refund', models.TextField(blank=True, null=True, verbose_name='Комментарий по возврату')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='internal_accounting.adultstudent', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Возврат средств (взрослый)',
                'verbose_name_plural': 'Возвраты средств (взрослые)',
                'ordering': ['-date_of_refund'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Порядковый номер в году')),
                ('statement_year', models.PositiveSmallIntegerField(db_index=True, editable=False, verbose_name='Год ведомости')),
                ('fio', encrypted_model_fields.fields.EncryptedCharField(verbose_name='ФИО ребенка')),
                ('phone_number', encrypted_model_fields.fields.EncryptedCharField(db_index=True, verbose_name='Номер телефона родителя')),
                ('parent_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='ФИО родителя/законного представителя')),
                ('course_name', models.CharField(choices=[('A', 'A'), ('A+B', 'A+B'), ('A1', 'A1'), ('A1+A+B', 'A1+A+B'), ('A1+B', 'A1+B'), ('АЗИЯ', 'АЗИЯ'), ('БАЗА', 'БАЗА'), ('БАЗА индив', 'БАЗА индив'), ('КОНТР', 'КОНТР'), ('КОНТР индив', 'КОНТР индив'), ('МИНИ', 'МИНИ'), ('МИНИ индив', 'МИНИ индив'), ('ПРО', 'ПРО'), ('ПРО индив', 'ПРО индив'), ('ПРОБНОЕ', 'ПРОБНОЕ'), ('ПРОБНОЕ индив', 'ПРОБНОЕ индив'), ('РАЗОВОЕ', 'РАЗОВОЕ'), ('РАЗОВОЕ индив', 'РАЗОВОЕ индив'), ('СЕКЦИЯ', 'СЕКЦИЯ'), ('СЕРТИФИКАТ', 'СЕРТИФИКАТ'), ('СТАНДАРТ', 'СТАНДАРТ'), ('СТАНДАРТ индив', 'СТАНДАРТ индив'), ('ЭКСТРА', 'ЭКСТРА'), ('ЭКСТРА индив', 'ЭКСТРА индив'), ('VIP', 'VIP')], max_length=50, verbose_name='Название курса')),
                ('total_hours', models.IntegerField(blank=True, null=True, verbose_name='Всего часов')),
                ('rolled_back_hours', models.IntegerField(default=0, verbose_name='Откатанные часы')),
                ('first_visit_date', models.DateField(blank=True, null=True, verbose_name='Первое посещение')),
                ('date_of_buyback', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('summ_of_payback', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('comment_for_payback', models.TextField(blank=True, null=True, verbose_name='Комментарий по оплате')),
                ('is_refund', models.BooleanField(default=False, verbose_name='Возврат средств')),
                ('summ_of_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма возврата')),
                ('is_in_office', models.BooleanField(default=False, verbose_name='В офисе')),
                ('is_manually_closed', models.BooleanField(default=False, verbose_name='Ведомость закрыта вручную')),
            ],
            options={
                'verbose_name': 'Детский студент',
                'verbose_name_plural': 'Детские студенты',
                'ordering': ['-statement_year', '-sequence_number'],
                'unique_together': {('sequence_number', 'statement_year')},
            },
        ),
        migrations.CreateModel(
            name='ChildRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_snapshot', models.CharField(max_length=255, verbose_name='ФИО ребенка (на момент возврата)')),
                ('course_name_snapshot', models.CharField(max_length=255, verbose_name='Курс (на момент возврата)')),
                ('summ_of_refund', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма возврата')),
                ('date_of_refund', models.DateField(default=datetime.date.today, verbose_name='Дата возврата')),
                ('comment_for_refund', models.TextField(blank=True, null=True, verbose_name='Комментарий по возврату')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='internal_accounting.child', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Возврат средств (детский)',
                'verbose_name_plural': 'Возвраты средств (детские)',
                'ordering': ['-date_of_refund'],
            },
        ),
    ]
