# Generated by Django 6.0.3 on 2026-03-28 00:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultstudent',
            name='summ_of_refund',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма возврата'),
        ),
        migrations.AlterField(
            model_name='child',
            name='summ_of_refund',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма возврата'),
        ),
    ]
