# Generated by Django 6.0.3 on 2026-03-28 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internal_accounting', '0002_alter_adultstudent_summ_of_refund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('adult', 'Взрослое'), ('child', 'Детское')], max_length=10, verbose_name='Направление')),
                ('instructor', models.CharField(choices=[('1', 'Инструктор 1'), ('2', 'Инструктор 2'), ('3', 'Инструктор 3'), ('4', 'Инструктор 4'), ('5', 'Инструктор 5')], max_length=10, verbose_name='Инструктор')),
                ('session_date', models.DateField(verbose_name='Дата занятия')),
                ('hours_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество часов')),
                ('hour_times', models.TextField(blank=True, null=True, verbose_name='Время занятий')),
                ('statement_number', models.CharField(editable=False, max_length=50, verbose_name='Номер ведомости')),
                ('course_name', models.CharField(editable=False, max_length=100, verbose_name='Курс')),
                ('student_fio', models.CharField(editable=False, max_length=255, verbose_name='ФИО студента')),
                ('total_hours', models.IntegerField(editable=False, null=True, verbose_name='Всего часов у студента')),
                ('rolled_back_hours_before', models.IntegerField(default=0, editable=False, verbose_name='Откатано до занятия')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('confirmed_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подтвердил')),
                ('rejected_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий инструктора')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий админа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('child_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_sessions', to='internal_accounting.child', verbose_name='Студент (детский)')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_sessions', to='internal_accounting.adultstudent', verbose_name='Студент (взрослый)')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Журнал занятий',
                'ordering': ['-session_date', '-created_at'],
                'indexes': [models.Index(fields=['session_date'], name='instructor__session_9ddac6_idx'), models.Index(fields=['status'], name='instructor__status_67f247_idx'), models.Index(fields=['instructor'], name='instructor__instruc_92b9d6_idx')],
            },
        ),
    ]
